config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'home/index'
  devise_for :users
  root to: 'home#index'
  get 'dashboard', to: 'campaigns#index', as: :dashboard

  resources :campaigns do
    member do
      get 'dashboard'
      get 'master', to: 'campaigns#master', as: :master_campaign
      get 'characters', to: 'campaigns#characters', as: :campaign_characters
      get 'player_dashboard', to: 'campaigns#player_dashboard', as: :player_dashboard
    end
    resources :characters, only: [:new, :create, :index, :edit, :update]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/Character.rb
class Character < ApplicationRecord
    belongs_to :campaign
    belongs_to :user
  end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user

  has_many :characters, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    # Associações existentes e módulos Devise
    has_many :campaigns, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campaign, only: %i[show edit update destroy dashboard master characters player_dashboard]

  def index
    @user_campaigns = current_user.campaigns.to_a
    @available_campaigns = Campaign.where.not(user: current_user).to_a
  end

  def show
    if @campaign.user == current_user
      redirect_to dashboard_campaign_path(@campaign)
    else
      redirect_to player_dashboard_campaign_path(@campaign)
    end
  end

  def new
    @campaign = current_user.campaigns.build
  end

  def edit
  end

  def create
    @campaign = current_user.campaigns.build(campaign_params)

    if @campaign.save
      redirect_to @campaign, notice: 'Campaign was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @campaign.update(campaign_params)
      redirect_to @campaign, notice: 'Campaign was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.'
  end

  def dashboard
  end

  def master
    # Lógica para mestrar a campanha
  end

  def characters
    @characters = @campaign.characters
    # Renderize a view para exibir os personagens
  end

  def player_dashboard
    @characters = @campaign.characters
    # Qualquer outra lógica necessária para o player_dashboard
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:id])
    if @campaign.user != current_user && action_name != 'player_dashboard'
      redirect_to player_dashboard_campaign_path(@campaign) and return
    end
  end

  def campaign_params
    params.require(:campaign).permit(:title, :description)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campaign, only: %i[new create index edit update]
  before_action :set_character, only: %i[edit update]
  before_action :check_campaign_owner, only: %i[edit update]

  def new
    @character = @campaign.characters.build
  end

  def create
    @character = @campaign.characters.build(character_params)
    @character.user = current_user

    if @character.save
      redirect_to campaign_characters_path(@campaign), notice: 'Character was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @characters = @campaign.characters
  end

  def edit
    if @is_owner
      render 'mestre_edit'
    elsif @character.ready
      redirect_to campaign_characters_path(@campaign, ready_alert: true)
    else
      render 'edit'
    end
  end

  def update
    if @character.update(character_params)
      redirect_to campaign_characters_path(@campaign), notice: 'Character was successfully updated.'
    else
      if @is_owner
        render 'mestre_edit'
      else
        render 'edit'
      end
    end
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end

  def set_character
    @character = @campaign.characters.find(params[:id])
  end

  def check_campaign_owner
    @is_owner = @campaign.user == current_user
  end

  def character_params
    params.require(:character).permit(:name, :description, :history, :height, :intelligence, :strength, :dexterity, :charisma, :constitution, :life, :mana, :status, :ready)
  end
end

app/controllers/dashboard_controller.rb
  class DashboardController < ApplicationController
    def index
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to dashboard_path  # ou qualquer outra rota desejada
    end
    # Se não estiver logado, simplesmente renderiza a view 'index' que é o comportamento padrão
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/campaigns/_campaign.html.erb
<div id="<%= dom_id campaign %>">
  <p>
    <strong>Title:</strong>
    <%= campaign.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= campaign.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= campaign.user_id %>
  </p>

</div>

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign) do |form| %>
  <% if campaign.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
        <% campaign.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/characters.html.erb
<h1>Personagens da Campanha: <%= @campaign.title %></h1>

<ul>
  <% if @characters.present? %>
    <% @characters.each do |character| %>
      <li>
        <%= character.name %> - <%= character.description %>
        <%= link_to 'Edit', edit_campaign_character_path(@campaign, character) %>
      </li>
    <% end %>
  <% else %>
    <li>Nenhum personagem encontrado.</li>
  <% end %>
</ul>
<%= link_to 'Criar novo personagem', new_campaign_character_path(@campaign) %>

app/views/campaigns/dashboard.html.erb
<h1><%= @campaign.title %> - Dashboard</h1>

<p>
  <%= link_to 'Mestrar Campanha', master_campaign_campaign_path(@campaign), class: 'btn btn-primary' %>
</p>
<p>
  <%= link_to 'Editar Campanha', edit_campaign_path(@campaign), class: 'btn btn-secondary' %>
</p>
<p>
  <%= link_to 'Exibir Personagens da Campanha', campaign_characters_campaign_path(@campaign), class: 'btn btn-info' %>
</p>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Show this campaign", @campaign %> |
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/index.html.erb
<%# app/views/dashboard/index.html.erb %>

<h1>Dashboard</h1>
<%= link_to 'Create New Campaign', new_campaign_path, class: 'btn btn-primary' %>

<div>
  <h2>Your Campaigns</h2>
  <ul>
    <% if @user_campaigns.present? %>
      <% @user_campaigns.each do |campaign| %>
        <li><%= link_to campaign.title, campaign_path(campaign) %></li>
      <% end %>
    <% else %>
      <li>No campaigns found.</li>
    <% end %>
  </ul>
</div>

<div>
  <h2>Available Campaigns</h2>
  <ul>
    <% if @available_campaigns.present? %>
      <% @available_campaigns.each do |campaign| %>
        <li><%= link_to campaign.title, campaign_path(campaign) %></li>
      <% end %>
    <% else %>
      <li>No available campaigns.</li>
    <% end %>
  </ul>
</div>

app/views/campaigns/master.html.erb
<h1>Mestrar Campanha: <%= @campaign.title %></h1>

<!-- Adicione aqui a lógica e interface para mestrar a campanha -->

app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/player_dashboard.html.erb
<% if params[:ready_alert] %>
  <script>
    alert('Character is ready and cannot be edited by players.');
  </script>
<% end %>

<h1>Personagens da Campanha: <%= @campaign.title %></h1>

<ul>
  <% if @characters.present? %>
    <% @characters.each do |character| %>
      <li>
        <%= character.name %> - <%= character.description %>
        <%= link_to 'Edit', edit_campaign_character_path(@campaign, character) %>
      </li>
    <% end %>
  <% else %>
    <li>Nenhum personagem encontrado.</li>
  <% end %>
</ul>
<%= link_to 'Criar novo personagem', new_campaign_character_path(@campaign) %>

app/views/campaigns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @campaign %>

<div>
  <%= link_to "Edit this campaign", edit_campaign_path(@campaign) %> |
  <%= link_to "Back to campaigns", campaigns_path %>

  <%= button_to "Destroy this campaign", @campaign, method: :delete %>
</div>

app/views/characters/edit.html.erb
<h1>Edit Character</h1>

<%= form_with(model: [@campaign, @character], local: true) do |form| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>
      <ul>
        <% @character.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.text_area :history %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height, step: :any, min: 0, max: 2.00 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', campaign_characters_path(@campaign) %>

app/views/characters/mestre_edit.html.erb
<h1>Edit Character</h1>

<%= form_with(model: [@campaign, @character], local: true) do |form| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>
      <ul>
        <% @character.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.text_area :history %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height, step: :any, min: 0, max: 2.00 %>
  </div>

  <div class="field">
    <%= form.label :intelligence %>
    <%= form.number_field :intelligence %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.number_field :strength %>
  </div>

  <div class="field">
    <%= form.label :dexterity %>
    <%= form.number_field :dexterity %>
  </div>

  <div class="field">
    <%= form.label :charisma %>
    <%= form.number_field :charisma %>
  </div>

  <div class="field">
    <%= form.label :constitution %>
    <%= form.number_field :constitution %>
  </div>

  <div class="field">
    <%= form.label :life %>
    <%= form.number_field :life %>
  </div>

  <div class="field">
    <%= form.label :mana %>
    <%= form.number_field :mana %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="field">
    <%= form.label :ready %>
    <%= form.check_box :ready %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', campaign_characters_path(@campaign) %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= form_with(model: [ @campaign, @character ]) do |form| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% @character.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.text_area :history %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :intelligence %>
    <%= form.number_field :intelligence %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.number_field :strength %>
  </div>

  <div class="field">
    <%= form.label :dexterity %>
    <%= form.number_field :dexterity %>
  </div>

  <div class="field">
    <%= form.label :charisma %>
    <%= form.number_field :charisma %>
  </div>

  <div class="field">
    <%= form.label :constitution %>
    <%= form.number_field :constitution %>
  </div>

  <div class="field">
    <%= form.label :life %>
    <%= form.number_field :life %>
  </div>

  <div class="field">
    <%= form.label :mana %>
    <%= form.number_field :mana %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', campaign_characters_path(@campaign) %>

app/views/dashboard/index.html.erb
<%# app/views/dashboard/index.html.erb %>

<h1>Dashboard</h1>
<%= link_to 'Create New Campaign', new_campaign_path, class: 'btn btn-primary' %>

<%# Abas para campanhas do usuário e outras campanhas %>
<ul class="nav nav-tabs" id="campaignTabs" role="tablist">
</ul>
<div class="tab-content" id="campaignTabsContent">
  <div class="tab-pane fade show active" id="user-campaigns" role="tabpanel" aria-labelledby="user-campaigns-tab">
    <h2>Your Campaigns</h2>
    <ul>
      <% current_user.campaigns.each do |campaign| %>
        <li><%= link_to campaign.title, campaign_path(campaign) %></li>
      <% end %>
    </ul>
  </div>
  <div class="tab-pane fade" id="available-campaigns" role="tabpanel" aria-labelledby="available-campaigns-tab">
    <h2>Available Campaigns</h2>
    <ul>
      <% Campaign.where.not(user: current_user).each do |campaign| %>
        <li><%= link_to campaign.title, campaign_path(campaign) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<h1>Bem-vindo ao Nosso Site!</h1>
<p>Bem vindo ao meu site etc.. etc..</p>
<a href="/users/sign_in" style="display: inline-block; padding: 10px 20px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px;">Login</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orpgp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>